events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        location /books {
            proxy_pass http://books-service:5001/books;
        }

        location /orders {
            proxy_pass http://orders-service:5002/orders;
        }

        location /health {
            return 200 "NGINX is up and running";
        }
    }
}
